name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t docker-demo .

      - name: Run Docker container
        run: docker run -d --name docker-demo-container -p 8000:8000 docker-demo

      - name: Test application
        run: |
		sleep 2
		docker logs docker-demo-container
		curl --fail http://localhost:8000

      - name: Stop container
        run: docker stop docker-demo-container
